define(['dust'], function() {
    (function(){dust.register("base/appLayout",body_0);function body_0(chk,ctx){return chk.write("<div id=\"header-region\" class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\"></div><div class=\"container-fluid\"><div class=\"row\"><div id=\"sidebar-region\" class=\"col-sm-3 col-md-2 sidebar\"></div><div id=\"main-region\" class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\"></div></div></div>");}return body_0;})();

    (function(){dust.register("base/publicLayout",body_0);function body_0(chk,ctx){return chk.write("<div class=\"cover-container\"><header id=\"header-region\" class=\"masthead clearfix\"></header><div id=\"main-region\"></div><footer id=\"footer-region\"></footer></div>");}return body_0;})();

    (function(){dust.register("dashboard/dashboard",body_0);function body_0(chk,ctx){return chk.write("<h1 class=\"page-header\">Dashboard</h1><div class=\"row placeholders\"><div class=\"col-xs-6 col-sm-3 placeholder\"><img data-src=\"holder.js/200x200/auto/sky\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\"><h4>Label</h4><span class=\"text-muted\">Something else</span></div><div class=\"col-xs-6 col-sm-3 placeholder\"><img data-src=\"holder.js/200x200/auto/vine\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\"><h4>Label</h4><span class=\"text-muted\">Something else</span></div><div class=\"col-xs-6 col-sm-3 placeholder\"><img data-src=\"holder.js/200x200/auto/sky\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\"><h4>Label</h4><span class=\"text-muted\">Something else</span></div><div class=\"col-xs-6 col-sm-3 placeholder\"><img data-src=\"holder.js/200x200/auto/vine\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\"><h4>Label</h4><span class=\"text-muted\">Something else</span></div></div><h2 class=\"sub-header\">Section title</h2><div class=\"table-responsive\"><table class=\"table table-striped\"><thead><tr><th>#</th><th>Header</th><th>Header</th><th>Header</th><th>Header</th></tr></thead><tbody><tr><td>1,001</td><td>Lorem</td><td>ipsum</td><td>dolor</td><td>sit</td></tr><tr><td>1,002</td><td>amet</td><td>consectetur</td><td>adipiscing</td><td>elit</td></tr><tr><td>1,003</td><td>Integer</td><td>nec</td><td>odio</td><td>Praesent</td></tr><tr><td>1,003</td><td>libero</td><td>Sed</td><td>cursus</td><td>ante</td></tr><tr><td>1,004</td><td>dapibus</td><td>diam</td><td>Sed</td><td>nisi</td></tr><tr><td>1,005</td><td>Nulla</td><td>quis</td><td>sem</td><td>at</td></tr><tr><td>1,006</td><td>nibh</td><td>elementum</td><td>imperdiet</td><td>Duis</td></tr><tr><td>1,007</td><td>sagittis</td><td>ipsum</td><td>Praesent</td><td>mauris</td></tr><tr><td>1,008</td><td>Fusce</td><td>nec</td><td>tellus</td><td>sed</td></tr><tr><td>1,009</td><td>augue</td><td>semper</td><td>porta</td><td>Mauris</td></tr><tr><td>1,010</td><td>massa</td><td>Vestibulum</td><td>lacinia</td><td>arcu</td></tr><tr><td>1,011</td><td>eget</td><td>nulla</td><td>Class</td><td>aptent</td></tr><tr><td>1,012</td><td>taciti</td><td>sociosqu</td><td>ad</td><td>litora</td></tr><tr><td>1,013</td><td>torquent</td><td>per</td><td>conubia</td><td>nostra</td></tr><tr><td>1,014</td><td>per</td><td>inceptos</td><td>himenaeos</td><td>Curabitur</td></tr><tr><td>1,015</td><td>sodales</td><td>ligula</td><td>in</td><td>libero</td></tr></tbody></table></div>");}return body_0;})();

    (function(){dust.register("features/features",body_0);function body_0(chk,ctx){return chk.write("<h2 class=\"cover-heading\">Features</h2><div class=\"row marketing\"><div class=\"col-lg-6\"><h4 class=\"text-primary\">Backbone + Marionette</h4><p>Backbone gives Mercenary its structure, while Marionette makes it more modularized and maintainable, with built-in event-aggregation, layouts, regions, and much more.</p><h4 class=\"text-primary\">requirejs + Bower</h4><p>requirejs makes dependency injection, concatenation and minification a breeze. Bower manages dependencies like a boss.</p><h4 class=\"text-primary\">Mocha + Chai</h4><p>Get your test on with runners in both the browser and on the command line. Write tests your way with <em>should</em>, <em>assert</em> and <em>expect</em>.</p><h4 class=\"text-primary\">LESS</h4><p>LESS is beautiful. From modularized stylesheets to variables and mixins, LESS is supercharged CSS.</p></div><div class=\"col-lg-6\"><h4 class=\"text-primary\">Node.js + Express</h4><p>Quick boot, no build, and blazing fast, Node.js and Express provide an awesome server-side web application architecture.</p><h4 class=\"text-primary\">Passport</h4><p>Authentication is already taken care of, so you can focus on getting users, not writing login logic. Users can sign up via email, or log in using Facebook, Twitter, Google, or Github.</p><h4 class=\"text-primary\">Grunt</h4><p>Somebody has to do the dirty work. With pre-configured tasks ranging from concatenation to deployment to running tests, Grunt's got you covered.</p><h4 class=\"text-primary\">MongoDB</h4><p>Support for MongoDB is baked in, but Mercenary can configured to work with virtually any data store.</p></div></div><p class=\"lead\"><a href=\"https://github.com/justinsisley/Mercenary\" class=\"btn btn-lg btn-default\">Learn more on Github</a></p>");}return body_0;})();

    (function(){dust.register("footer/publicFooter",body_0);function body_0(chk,ctx){return chk.write("<div class=\"inner\"><p>Cover template for <a href=\"http://getbootstrap.com\">Bootstrap</a>, by <a href=\"https://twitter.com/mdo\">@mdo</a>.</p></div>");}return body_0;})();

    (function(){dust.register("header/appHeader",body_0);function body_0(chk,ctx){return chk.write("<div class=\"container-fluid\"><div class=\"navbar-header\"><button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"><span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span></button><a class=\"navbar-brand\" href=\"/dashboard\">Mercenary</a></div><div class=\"navbar-collapse collapse\"><ul class=\"nav navbar-nav navbar-right\"><li><a href=\"/dashboard\">Dashboard</a></li><li><a href=\"/settings\">Settings</a></li><li><a href=\"/profile\">Profile</a></li><li><a href=\"/help\">Help</a></li><li><a href=\"/logout\" id=\"js-logout-link\">Log Out</a></li></ul><form class=\"navbar-form navbar-right\"><input type=\"text\" class=\"form-control\" placeholder=\"Search...\"></form></div></div>");}return body_0;})();

    (function(){dust.register("header/publicHeader",body_0);function body_0(chk,ctx){return chk.write("<h3 class=\"masthead-brand\"><a href=\"/\">Mercenary</a></h3><ul class=\"nav masthead-nav\"><li class=\"nav-home\"><a href=\"/\">Home</a></li><li class=\"nav-features\"><a href=\"/features\">Features</a></li><li class=\"nav-login\"><a href=\"/login\">Log In</a></li><li class=\"nav-signup\"><a href=\"/signup\">Sign Up</a></li></ul>");}return body_0;})();

    (function(){dust.register("home/home",body_0);function body_0(chk,ctx){return chk.write("<h2 class=\"cover-heading\">The Force Multiplier Web Application Stack</h2><p class=\"lead\">Mercenary is a full-featured, single-page web application based on <a href=\"http://backbonejs.org/\" target=\"_blank\">Backbone</a>, <a href=\"http://marionettejs.com/\" target=\"_blank\">Marionette</a>, <a href=\"http://requirejs.org/\" target=\"_blank\">requirejs</a>, <a href=\"http://expressjs.com/\" target=\"_blank\">Express</a> and <a href=\"http://gruntjs.com/\" target=\"_blank\">Grunt</a>. Bend it to your will and <strong>make something beautiful</strong>.</p><p class=\"lead\"><a href=\"https://github.com/justinsisley/Mercenary\" class=\"btn btn-lg btn-default\">Learn more on Github</a></p>");}return body_0;})();

    (function(){dust.register("login/login",body_0);function body_0(chk,ctx){return chk.write("<p class=\"lead\">You're already using Mercenary.</p><p class=\"sub-lead\">Authentication is baked-in. Log in to see the dashboard.</p><form class=\"form-signin\" role=\"form\" action=\"/users/signin\" method=\"post\"><h3 class=\"form-signin-heading\">Log in to your account</h3><input id=\"js-login-email\" type=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Email address\" autofocus>    <input id=\"js-login-password\" type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Password\"><button class=\"btn btn-lg btn-primary btn-block\" id=\"js-login-submit\" type=\"submit\">Log in</button><div class=\"alert alert-danger hidden\" id=\"js-form-error-message\">&nbsp;</div><div class=\"alert alert-success hidden\" id=\"js-form-success-message\">&nbsp;</div><p class=\"lead form-signup-social\">Or, sign in via...</p><div class=\"row\"><a class=\"btn btn-primary btn-facebook\" href=\"/auth/facebook\">Facebook</a><a class=\"btn btn-primary btn-google\" href=\"/auth/google\">Google</a><a class=\"btn btn-primary btn-twitter\" href=\"/auth/twitter\">Twitter</a><a class=\"btn btn-primary btn-github\" href=\"/auth/github\">GitHub</a></div></form>");}return body_0;})();

    (function(){dust.register("sidebar/sidebar",body_0);function body_0(chk,ctx){return chk.write("<ul class=\"nav nav-sidebar\"><li class=\"active\"><a href=\"#\">Overview</a></li><li><a href=\"#\">Reports</a></li><li><a href=\"#\">Analytics</a></li><li><a href=\"#\">Export</a></li></ul><ul class=\"nav nav-sidebar\"><li><a href=\"\">Nav item</a></li><li><a href=\"\">Nav item again</a></li><li><a href=\"\">One more nav</a></li><li><a href=\"\">Another nav item</a></li><li><a href=\"\">More navigation</a></li></ul><ul class=\"nav nav-sidebar\"><li><a href=\"\">Nav item again</a></li><li><a href=\"\">One more nav</a></li><li><a href=\"\">Another nav item</a></li></ul>");}return body_0;})();

    (function(){dust.register("signup/signup",body_0);function body_0(chk,ctx){return chk.write("<p class=\"lead\">You're already using Mercenary.</p><p class=\"sub-lead\">Authentication is baked-in. Create an account and give it a test drive.</p><form class=\"form-signin\" role=\"form\"><h3 class=\"form-signin-heading\">Create an account</h3><input id=\"js-signup-email\" type=\"email\" class=\"form-control\" placeholder=\"Email address\" required autofocus><input id=\"js-signup-password\" type=\"password\" class=\"form-control\" placeholder=\"Password\" required><button class=\"btn btn-lg btn-primary btn-block\" id=\"js-signup-submit\" type=\"submit\">Sign up</button><div class=\"alert alert-danger hidden\" id=\"js-form-error-message\">&nbsp;</div><div class=\"alert alert-success hidden\" id=\"js-form-success-message\">&nbsp;</div><p class=\"lead form-signup-social\">Or, sign in via...</p><div class=\"row\"><a class=\"btn btn-primary btn-facebook\" href=\"/auth/facebook\">Facebook</a><a class=\"btn btn-primary btn-google\" href=\"/auth/google\">Google</a><a class=\"btn btn-primary btn-twitter\" href=\"/auth/twitter\">Twitter</a><a class=\"btn btn-primary btn-github\" href=\"/auth/github\">GitHub</a></div></form>");}return body_0;})();
});